project:
  type: website
  output-dir: docs

website:
  title: "c.q. blog"
  site-url: https://econ-space.github.io/
  description: "A blog by a Japanese PhD student in Economics based in Switzerland | スイスで経済学PhDを目指す日本人のブログ"
  open-graph: true
  twitter-card: true
  # draft-mode: unlinked
  navbar:
    left: []
  search: true

format:
  html:
    toc: true
    toc-depth: 3
    theme:
      light: [flatly, css/theme.scss]
      # dark: [darkly, css/theme-dark.scss]
    css: css/custom.css
    fontsize: 1.0em
    code-copy: true
    code-overflow: wrap

webr: 
  show-startup-message: false
  show-header-message: false
  channel-type: 'post-message'
