---
title: "One economist's wisdom"
date: "2025-06-20"
categories: 
  - life
  - research
---
Lately, my motivation hasn't been particularly high. A mix of ongoing issues and various annoying commitments has been wearing me down. And, unfortunately, I don't really have anyone in this city I can talk to casually or spontaneously, either (my spouse is currently in Japan). That said, I'm still working on my R&R with my coauthors and continuing to study a theoretical (econometric) topic I'm currently into.

Every time I hit a low point, and I remember this article, I go back and read it. It always gives me a lift.
The paragraph below is from Rubinstein (2013), a rather unusual and personal article where he responds to ten questions aimed at helping "lost" graduate students in economics. I find this particular answer both grounding and moving. It's one of those things I come back to when I need to remind myself what a rare opportunity I've been given, and how how fortunate I am to have it.

> **Q10. Finally, do you have anything serious to say?**

> Sure, everything I have said here is very serious. But let me add a final comment: Remember that you are one of the most privileged people on earth. Society has given you a wonderful opportunity. You are supposed to do whatever you want, to think about new ideas, to express your views freely, to do things in the way that you choose, and on top of that you will be rewarded nicely for doing so. These privileges should not be taken for granted. We are extremely lucky, and we owe something in return.

Ariel Rubinstein is an Israeli economist.

Given the current circumstances, and the fact that I have an Israeli friend here, it's hard not to feel heartache when I think about what many people are going through right now.

Thanks for reading this far.  
(∗ ˊωˋ ∗)

> Rubinstein, A. (2013). 10 Q&A: Experienced Advice for “Lost” Graduate Students in Economics. The Journal of Economic Education, 44(3), 193–196. https://doi.org/10.1080/00220485.2013.795448
